port: 8080
database:
  host: containers-us-west-185.railway.app
  port: 6921
  user: root
  password: ntyZKoicP3fwC59xljmv
  name: bdnube



#  name: backenProducto
# host: 127.0.0.1
# password: Gmd123456**

# host: 192.168.1.101
#  port: 3306
#  user: darwin
#  password: 123456
#  name: test

# usuario generico solo la basedatos
# qrtomfoto
# Tom123456**-'